const ADD_INVENTORY_ITEM = 'ADD_INVENTORY_ITEM';
const REMOVE_INVENTORY_ITEM = 'REMOVE_INVENTORY_ITEM';
const CHANGE_INVENTORY_ITEM_FIELD_VALUE = 'CHANGE_INVENTORY_ITEM_FIELD_VALUE';
const SET_INVENTORY_TYPE_FILTER = 'SET_INVENTORY_TYPE_FILTER';
const ADD_TYPE = 'ADD_TYPE';
const REMOVE_TYPE = 'REMOVE_TYPE';
const ADD_TYPE_FIELD = 'ADD_TYPE_FIELD';
const REMOVE_TYPE_FIELD = 'REMOVE_TYPE_FIELD';
const MODIFY_TYPE_FIELD_NAME = 'MODIFY_TYPE_FIELD_NAME';
const MODIFY_TYPE_FIELD_TYPE = 'MODIFY_TYPE_FIELD_TYPE';
const MODIFY_TYPE_TITLE_FIELD = 'MODIFY_TYPE_TITLE_FIELD';
const MODIFY_TYPE_NAME = 'MODIFY_TYPE_NAME';

export {
  ADD_INVENTORY_ITEM,
  REMOVE_INVENTORY_ITEM,
  CHANGE_INVENTORY_ITEM_FIELD_VALUE,
  SET_INVENTORY_TYPE_FILTER,
  ADD_TYPE,
  REMOVE_TYPE,
  ADD_TYPE_FIELD,
  REMOVE_TYPE_FIELD,
  MODIFY_TYPE_FIELD_NAME,
  MODIFY_TYPE_FIELD_TYPE,
  MODIFY_TYPE_TITLE_FIELD,
  MODIFY_TYPE_NAME,
};
